name: senior-design
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.4
  - cryptography=41.0.3
  - daal4py=2023.1.1
  - dal=2023.1.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2022.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=4.1.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.1.4
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=3.11.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytorch=2.1.0
  - pyyaml=6.0.1
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.2.2
  - scikit-learn-intelex=2023.1.1
  - scipy=1.11.3
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchvision=0.16.0
  - tornado=6.3.3
  - traitlets=5.13.0
  - urllib3=1.26.18
  - wcwidth=0.2.9
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - beautifulsoup4==4.12.2
      - cachetools==5.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.14.6
      - dill==0.3.7
      - fastapi==0.104.1
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - funcy==2.0
      - gensim==4.3.2
      - google==3.0.0
      - google-api-core==2.13.0
      - google-api-python-client==2.107.0
      - google-auth==2.23.4
      - google-auth-httplib2==0.1.1
      - google-auth-oauthlib==1.1.0
      - google-pasta==0.2.0
      - googleapi==0.1.0
      - googleapis-common-protos==1.61.0
      - h11==0.14.0
      - httplib2==0.22.0
      - huggingface-hub==0.17.3
      - ipywidgets==8.1.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - matplotlib==3.8.1
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nltk==3.8.1
      - numexpr==2.8.7
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - pandas==2.1.2
      - protobuf==4.25.0
      - pyarrow==14.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pyldavis==3.4.1
      - pyparsing==3.1.1
      - pytube==15.0.0
      - pytz==2023.3.post1
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.0
      - smart-open==6.4.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - starlette==0.27.0
      - tokenizers==0.14.1
      - tqdm==4.66.1
      - transformers==4.35.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uritemplate==4.1.1
      - uvicorn==0.24.0.post1
      - widgetsnbextension==4.0.9
      - wordcloud==1.9.2
      - xxhash==3.4.1
      - yarl==1.9.2
      - youtube-transcript-api==0.6.1
